vich_uploader:
    db_driver: orm

    mappings:
        game_picture:
#          J indique ou doit se positionner l image
            uri_prefix: assets/img/pictures
#          J aindique dans quel dissier l'image est sauvee.
            upload_destination: '%kernel.project_dir%/public/assets/img/pictures'



        game_rule:
            uri_prefix: assets/img/game_rule
            upload_destination: '%kernel.project_dir%/public/assets/img/game_rule'


